import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'te' | 'hi' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const toggleLanguage = () => {
    const languages: Language[] = ['en', 'te', 'hi', 'gu'];
    const currentIndex = languages.indexOf(language);
    const nextIndex = (currentIndex + 1) % languages.length;
    setLanguage(languages[nextIndex]);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  useEffect(() => {
    // In React Native, handle RTL or other locale-specific behavior if needed
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Comprehensive Translations
const translations: Record<Language, any> = {
  en: {
    common: {
      search: 'Search poojas...',
      viewAll: 'View All',
      upcoming: 'Upcoming',
      active: 'Active',
      completed: 'Completed',
      cancel: 'Cancel',
      save: 'Save',
      continue: 'Continue',
      back: 'Back',
      edit: 'Edit',
      signOut: 'Sign Out',
      close: 'Close',
      viewDetails: 'View Details',
      bookNow: 'Book Now',
      free: 'Free',
      included: 'Included',
      clearAll: 'Clear All',
    },
    nav: {
      home: 'Home',
      poojas: 'Poojas',
      bookings: 'Bookings',
      temples: 'Temples',
      profile: 'Profile',
    },
    home: {
      greeting: 'Namaste',
      subtitle: 'Today is Ekadashi — an auspicious day for Vishnu poojas.',
      featuredTemples: 'Featured Temples',
      categories: 'Pooja Categories',
      upcomingPoojas: 'Upcoming Poojas',
      notifications: 'Notifications',
      noNotifications: 'No new notifications',
      viewNotification: 'View',
      recommendedForYou: 'Recommended for You',
      basedOnNakshatra: 'Based on your Nakshatra',
    },
    categories: {
      abhishekam: 'Abhishekam',
      homam: 'Homam',
      archana: 'Archana',
      specialPoojas: 'Special Poojas',
      all: 'All Poojas',
    },
    poojas: {
      title: 'Sacred Poojas',
      subtitle: 'Discover authentic temple rituals',
      searchPlaceholder: 'Search poojas...',
      filters: 'Filters',
      noPoojas: 'No poojas found',
      liveStream: 'Live Stream Available',
      prasadIncluded: 'Prasad Included',
      duration: 'Duration',
      min: 'min',
    },
    poojaDetail: {
      overview: 'Overview',
      where: 'Where',
      how: 'How',
      why: 'Why',
      offerPooja: 'Offer This Pooja',
      sevaAmount: 'Seva Amount',
      duration: 'Duration',
      liveStreamAvailable: 'Live Stream Available',
      prasadIncluded: 'Prasad Included',
      whereTitle: 'Where this pooja is conducted',
      howTitle: 'How this pooja is conducted',
      whyTitle: 'Why devotees offer this pooja',
      suitableForRashi: 'Suitable for Rashi',
      blessings: 'Blessings',
    },
    booking: {
      selectDateTime: 'Select Date & Time',
      yourDetails: 'Your Details',
      reviewConfirm: 'Review & Confirm',
      selectDate: 'Select Date',
      selectTime: 'Select Time',
      devoteeNames: 'Devotee Name(s)',
      devoteeNamesDesc: 'The pooja will be performed in these names',
      devoteeNamesPlaceholder: 'Enter names',
      gothram: 'Gothram',
      gothramPlaceholder: 'Enter Gothram',
      nakshatra: 'Nakshatra',
      nakshatraPlaceholder: 'Select Nakshatra',
      specialRequests: 'Special Requests',
      specialRequestsPlaceholder: 'Any specific prayers or intentions...',
      poojaDetails: 'Pooja Details',
      paymentSummary: 'Payment Summary',
      poojaAmount: 'Pooja Amount',
      prasadDelivery: 'Prasad Delivery',
      liveStream: 'Live Stream',
      totalAmount: 'Total Amount',
      proceedToPayment: 'Proceed to Payment',
      note: 'Note',
      confirmationNote: 'You will receive a confirmation with booking details and live stream link once payment is complete.',
    },
    bookingConfirmation: {
      title: 'Your Seva Has Been Offered',
      subtitle: 'The pooja will be performed in your name and Gothram. May the blessings be with you and your family.',
      bookingConfirmed: 'Booking Confirmed',
      bookingId: 'Booking ID',
      viewJourney: 'View Full Journey',
      backToHome: 'Back to Home',
    },
    bookings: {
      title: 'My Bookings',
      subtitle: 'Track your pooja journey',
      active: 'Active',
      completed: 'Completed',
      noActive: 'No active bookings',
      noCompleted: 'No completed bookings',
      noActiveDesc: 'Book your first pooja to get started',
      noCompletedDesc: 'Your completed poojas will appear here',
      viewJourney: 'View Full Journey',
      watchRecording: 'Watch Recording',
      trackPrasad: 'Track Prasad',
      poojaJourney: 'Pooja Journey',
    },
    journey: {
      title: 'Pooja Journey',
      sevaOffered: 'Seva Offered',
      pujariAssigned: 'Pujari Assigned',
      confirmed: 'Confirmed',
      poojaScheduled: 'Scheduled',
      goingLive: 'Pooja Live',
      poojaCompleted: 'Completed',
      recordingReady: 'Recording Ready',
      prasadPacked: 'Prasad Packed',
      prasadDispatched: 'Dispatched',
      prasadDelivered: 'Delivered',
    },
    temples: {
      title: 'Sacred Temples',
      subtitle: 'Explore divine temples',
      explore: 'Explore',
      hide: 'Hide',
      availablePoojas: 'Available Poojas',
      location: 'Location',
    },
    profile: {
      title: 'Profile',
      personalisation: 'Personalisation',
      aiRecommendations: 'Your Sacred Recommendations',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      notifications: 'Notifications',
      hinduCalendar: 'Hindu Calendar',
      helpSupport: 'Help & Support',
      appSettings: 'App Settings',
      signOut: 'Sign Out',
      version: 'Made with devotion',
      editProfile: 'Edit Profile',
      editPersonalInfo: 'Edit Personal Information',
      fullName: 'Full Name',
      email: 'Email',
      phone: 'Phone',
      location: 'Location',
      nakshatra: 'Nakshatra',
      rashi: 'Rashi',
      dateOfBirth: 'Date of Birth',
      gothram: 'Gothram',
      saveChanges: 'Save Changes',
      recommendationsTitle: 'Based on Your Nakshatra',
      recommendationsDesc: 'Personalised pooja recommendations just for you',
      viewRecommendations: 'View Recommendations',
      totalPoojas: 'Poojas',
      upcomingCount: 'Upcoming',
      devotionScore: 'Devotion',
    },
    notifications: {
      title: 'Notification Settings',
      poojaReminders: 'Pooja Reminders',
      poojaRemindersDesc: 'Get reminded before your scheduled poojas',
      liveStreams: 'Live Streams',
      liveStreamsDesc: 'Notification when your pooja starts streaming',
      prasadUpdates: 'Prasad Updates',
      prasadUpdatesDesc: 'Track your prasad delivery status',
      festivalAlerts: 'Festival Alerts',
      festivalAlertsDesc: 'Special poojas and festival notifications',
      saveSettings: 'Save Settings',
    },
    calendar: {
      title: 'Hindu Calendar',
      todayTithi: "Today's Tithi",
      upcomingFestivals: 'Upcoming Festivals',
    },
    help: {
      title: 'Help & Support',
      contactSupport: 'Contact Support',
      faq: 'Frequently Asked Questions',
    },
    language: {
      label: 'Language',
      english: 'English',
      telugu: 'తెలుగు',
      hindi: 'हिंदी',
      gujarati: 'ગુજરાતી',
    },
  },
  te: {
    common: {
      search: 'పూజలను వెతకండి...',
      viewAll: 'అన్నీ చూడండి',
      upcoming: 'రాబోయే',
      active: 'క్రియాశీల',
      completed: 'పూర్తయింది',
      cancel: 'రద్దు చేయండి',
      save: 'భద్రపరచండి',
      continue: 'కొనసాగించండి',
      back: 'వెనుకకు',
      edit: 'సవరించండి',
      signOut: 'సైన్ అవుట్',
      close: 'మూసివేయండి',
      viewDetails: 'వివరాలు చూడండి',
      bookNow: 'ఇప్పుడే బుక్ చేయండి',
      free: 'ఉచితం',
      included: 'చేర్చబడింది',
      clearAll: 'అన్ని తుడించండి',
    },
    nav: {
      home: 'హోమ్',
      poojas: 'పూజలు',
      bookings: 'బుకింగ్‌లు',
      temples: 'ఆలయాలు',
      profile: 'ప్రొఫైల్',
    },
    home: {
      greeting: 'నమస్తే',
      subtitle: 'ఈరోజు ఏకాదశి — విష్ణు పూజలకు శుభ దినం.',
      featuredTemples: 'ప్రముఖ ఆలయాలు',
      categories: 'పూజా వర్గాలు',
      upcomingPoojas: 'రాబోయే పూజలు',
      notifications: 'నోటిఫికేషన్‌లు',
      noNotifications: 'కొత్త నోటిఫికేషన్‌లు లేవు',
      viewNotification: 'చూడండి',
      recommendedForYou: 'మీ కోసం సిఫార్సు చేయబడింది',
      basedOnNakshatra: 'మీ నక్షత్రం ఆధారంగా',
    },
    categories: {
      abhishekam: 'అభిషేకం',
      homam: 'హోమం',
      archana: 'అర్చన',
      specialPoojas: 'ప్రత్యేక పూజలు',
      all: 'అన్ని పూజలు',
    },
    poojas: {
      title: 'పవిత్ర పూజలు',
      subtitle: 'ప్రామాణికమైన ఆలయ ఆచారాలను కనుగొనండి',
      searchPlaceholder: 'పూజలను వెతకండి...',
      filters: 'ఫిల్టర్‌లు',
      noPoojas: 'పూజలు కనుగొనబడలేదు',
      liveStream: 'లైవ్ స్ట్రీమ్ అందుబాటులో ఉంది',
      prasadIncluded: 'ప్రసాదం చేర్చబడింది',
      duration: 'వ్యవధి',
      min: 'నిమి',
    },
    poojaDetail: {
      overview: 'అవలోకనం',
      where: 'ఎక్కడ',
      how: 'ఎలా',
      why: 'ఎందుకు',
      offerPooja: 'ఈ పూజను సమర్పించండి',
      sevaAmount: 'సేవా మొత్తం',
      duration: 'వ్యవధి',
      liveStreamAvailable: 'లైవ్ స్ట్రీమ్ అందుబాటులో ఉంది',
      prasadIncluded: 'ప్రసాదం చేర్చబడింది',
      whereTitle: 'ఈ పూజ ఎక్కడ నిర్వహించబడుతుంది',
      howTitle: 'ఈ పూజ ఎలా నిర్వహించబడుతుంది',
      whyTitle: 'భక్తులు ఈ పూజను ఎందుకు సమర్పిస్తారు',
      suitableForRashi: 'రాశికి అనుకూలమైనది',
      blessings: 'ఆశీర్వాదాలు',
    },
    booking: {
      selectDateTime: 'తేదీ మరియు సమయాన్ని ఎంచుకోండి',
      yourDetails: 'మీ వివరాలు',
      reviewConfirm: 'సమీక్షించండి మరియు నిర్ధారించండి',
      selectDate: 'తేదీని ఎంచుకోండి',
      selectTime: 'సమయాన్ని ఎంచుకోండి',
      devoteeNames: 'భక్తుల పేర్లు',
      devoteeNamesDesc: 'ఈ పేర్లలో పూజ నిర్వహించబడుతుంది',
      devoteeNamesPlaceholder: 'పేర్లు నమోదు చేయండి',
      gothram: 'గోత్రం',
      gothramPlaceholder: 'గోత్రం నమోదు చేయండి',
      nakshatra: 'నక్షత్రం',
      nakshatraPlaceholder: 'నక్షత్రం ఎంచుకోండి',
      specialRequests: 'ప్రత్యేక అభ్యర్థనలు',
      specialRequestsPlaceholder: 'ఏదైనా నిర్దిష్ట ప్రార్థనలు లేదా ఉద్దేశాలు...',
      poojaDetails: 'పూజా వివరాలు',
      paymentSummary: 'చెల్లింపు సారాంశం',
      poojaAmount: 'పూజా మొత్తం',
      prasadDelivery: 'ప్రసాదం డెలివరీ',
      liveStream: 'లైవ్ స్ట్రీమ్',
      totalAmount: 'మొత్తం మొత్తం',
      proceedToPayment: 'చెల్లింపుకు కొనసాగండి',
      note: 'గమనిక',
      confirmationNote: 'చెల్లింపు పూర్తయిన తర్వాత మీరు బుకింగ్ వివరాలు మరియు లైవ్ స్ట్రీమ్ లింక్‌తో నిర్ధారణను అందుకుంటారు.',
    },
    bookingConfirmation: {
      title: 'మీ సేవ సమర్పించబడింది',
      subtitle: 'మీ పేరు మరియు గోత్రంలో పూజ నిర్వహించబడుతుంది. మీకు మరియు మీ కుటుంబానికి ఆశీర్వాదాలు ఉండాలి.',
      bookingConfirmed: 'బుకింగ్ నిర్ధారించబడింది',
      bookingId: 'బుకింగ్ ఐడి',
      viewJourney: 'పూర్తి ప్రయాణాన్ని చూడండి',
      backToHome: 'హోమ్‌కు తిరిగి వెళ్ళండి',
    },
    bookings: {
      title: 'నా బుకింగ్‌లు',
      subtitle: 'మీ పూజా ప్రయాణాన్ని ట్రాక్ చేయండి',
      active: 'క్రియాశీల',
      completed: 'పూర్తయింది',
      noActive: 'క్రియాశీల బుకింగ్‌లు లేవు',
      noCompleted: 'పూర్తయిన బుకింగ్‌లు లేవు',
      noActiveDesc: 'మీ మొదటి పూజను బుక్ చేయండి',
      noCompletedDesc: 'పూర్తయిన పూజలు ఇక్కడ కనిపిస్తాయి',
      viewJourney: 'పూర్తి ప్రయాణాన్ని చూడండి',
      watchRecording: 'రికార్డింగ్ చూడండి',
      trackPrasad: 'ప్రసాదాన్ని ట్రాక్ చేయండి',
      poojaJourney: 'పూజా ప్రయాణం',
    },
    journey: {
      title: 'పూజా ప్రయాణం',
      sevaOffered: 'సేవ సమర్పించబడింది',
      pujariAssigned: 'పూజారి నియమించబడ్డారు',
      confirmed: 'నిర్ధారించబడింది',
      poojaScheduled: 'షెడ్యూల్ చేయబడింది',
      goingLive: 'పూజ లైవ్',
      poojaCompleted: 'పూర్తయింది',
      recordingReady: 'రికార్డింగ్ సిద్ధంగా ఉంది',
      prasadPacked: 'ప్రసాదం ప్యాక్ చేయబడింది',
      prasadDispatched: 'పంపబడింది',
      prasadDelivered: 'డెలివరీ చేయబడింది',
    },
    temples: {
      title: 'పవిత్ర ఆలయాలు',
      subtitle: 'దివ్య ఆలయాలను అన్వేషించండి',
      explore: 'అన్వేషించండి',
      hide: 'దాచండి',
      availablePoojas: 'అందుబాటులో ఉన్న పూజలు',
      location: 'స్థానం',
    },
    profile: {
      title: 'ప్రొఫైల్',
      personalisation: 'వ్యక్తిగతీకరణ',
      aiRecommendations: 'మీ పవిత్ర సిఫార్సులు',
      settings: 'సెట్టింగ్‌లు',
      theme: 'థీమ్',
      darkMode: 'డార్క్ మోడ్',
      lightMode: 'లైట్ మోడ్',
      notifications: 'నోటిఫికేషన్‌లు',
      hinduCalendar: 'హిందూ క్యాలెండర్',
      helpSupport: 'సహాయం & మద్దతు',
      appSettings: 'యాప్ సెట్టింగ్‌లు',
      signOut: 'సైన్ అవుట్',
      version: 'భక్తితో తయారు చేయబడింది',
      editProfile: 'ప్రొఫైల్‌ను సవరించండి',
      editPersonalInfo: 'వ్యక్తిగత సమాచారాన్ని సవరించండి',
      fullName: 'పూర్తి పేరు',
      email: 'ఇమెయిల్',
      phone: 'ఫోన్',
      location: 'స్థానం',
      nakshatra: 'నక్షత్రం',
      rashi: 'రాశి',
      dateOfBirth: 'పుట్టిన తేదీ',
      gothram: 'గోత్రం',
      saveChanges: 'మార్పులను భద్రపరచండి',
      recommendationsTitle: 'మీ నక్షత్రం ఆధారంగా',
      recommendationsDesc: 'మీ కోసం వ్యక్తిగతీకరించిన పూజా సిఫార్సులు',
      viewRecommendations: 'సిఫార్సులను చూడండి',
      totalPoojas: 'పూజలు',
      upcomingCount: 'రాబోయేవి',
      devotionScore: 'భక్తి',
    },
    notifications: {
      title: 'నోటిఫికేషన్ సెట్టింగ్‌లు',
      poojaReminders: 'పూజా రిమైండర్‌లు',
      poojaRemindersDesc: 'మీ షెడ్యూల్ చేసిన పూజలకు ముందు రిమైండర్ పొందండి',
      liveStreams: 'లైవ్ స్ట్రీమ్‌లు',
      liveStreamsDesc: 'మీ పూజ స్ట్రీమింగ్ ప్రాરంభమైనప్పుడు నోటిఫికేషన్',
      prasadUpdates: 'ప్రసాదం నవీకరణలు',
      prasadUpdatesDesc: 'మీ ప్రసాదం డెలివరీ స్థితిని ట్రాక్ చేయండి',
      festivalAlerts: 'పండుగ హెచ్చరికలు',
      festivalAlertsDesc: 'ప్రత్యేక పూజలు మరియు పండుగ నోటిఫికేషన్‌లు',
      saveSettings: 'సెట్టింగ్‌లను భద్రపరచండి',
    },
    calendar: {
      title: 'హిందూ క్యాలెండర్',
      todayTithi: 'నేటి తిథి',
      upcomingFestivals: 'రాబోయే పండుగలు',
    },
    help: {
      title: 'సహాయం & మద్దతు',
      contactSupport: 'మద్దతును సంప్రదించండి',
      faq: 'తరచుగా అడిగే ప్రశ్నలు',
    },
    language: {
      label: 'భాష',
      english: 'English',
      telugu: 'తెలుగు',
      hindi: 'हिंदी',
      gujarati: 'ગુજરાતી',
    },
  },
  hi: {
    common: {
      search: 'पूजा खोजें...',
      viewAll: 'सभी देखें',
      upcoming: 'आगामी',
      active: 'सक्रिय',
      completed: 'पूर्ण',
      cancel: 'रद्द करें',
      save: 'सहेजें',
      continue: 'जारी रखें',
      back: 'वापस',
      edit: 'संपादित करें',
      signOut: 'साइन आउट',
      close: 'बंद करें',
      viewDetails: 'विवरण देखें',
      bookNow: 'अभी बुक करें',
      free: 'मुफ़्त',
      included: 'शामिल',
      clearAll: 'सब कुछ साफ़ करें',
    },
    nav: {
      home: 'होम',
      poojas: 'पूजा',
      bookings: 'बुकिंग',
      temples: 'मंदिर',
      profile: 'प्रोफ़ाइल',
    },
    home: {
      greeting: 'नमस्ते',
      subtitle: 'आज एकादशी है — विष्णु पूजा के लिए शुभ दिन।',
      featuredTemples: 'विशेष मंदिर',
      categories: 'पूजा श्रेणियाँ',
      upcomingPoojas: 'आगामी पूजा',
      notifications: 'सूचनाएं',
      noNotifications: 'कोई नई सूचना नहीं',
      viewNotification: 'देखें',
      recommendedForYou: 'आपके लिए अनुशंसित',
      basedOnNakshatra: 'आपके नक्षत्र के आधार पर',
    },
    categories: {
      abhishekam: 'अभिषेक',
      homam: 'होमम',
      archana: 'अर्चना',
      specialPoojas: 'विशेष पूजा',
      all: 'सभी पूजा',
    },
    poojas: {
      title: 'पवित्र पूजा',
      subtitle: 'प्रामाणिक मंदिर अनुष्ठान खोजें',
      searchPlaceholder: 'पूजा खोजें...',
      filters: 'फ़िल्टर',
      noPoojas: 'कोई पूजा नहीं मिली',
      liveStream: 'लाइव स्ट्रीम उपलब्ध',
      prasadIncluded: 'प्रसाद शामिल',
      duration: 'अवधि',
      min: 'मिनट',
    },
    poojaDetail: {
      overview: 'अवलोकन',
      where: 'कहाँ',
      how: 'कैसे',
      why: 'क्यों',
      offerPooja: 'यह पूजा अर्पित करें',
      sevaAmount: 'सेवा राशि',
      duration: 'अवधि',
      liveStreamAvailable: 'लाइव स्ट्रीम उपलब्ध',
      prasadIncluded: 'प्रसाद शामिल',
      whereTitle: 'यह पूजा कहाँ आयोजित की जाती है',
      howTitle: 'यह पूजा कैसे आयोजित की जाती है',
      whyTitle: 'भक्त इस पूजा को क्यों अर्पित करते हैं',
      suitableForRashi: 'राशि के लिए उपयुक्त',
      blessings: 'आशीर्वाद',
    },
    booking: {
      selectDateTime: 'तिथि और समय चुनें',
      yourDetails: 'आपका विवरण',
      reviewConfirm: 'समीक्षा और पुष्टि करें',
      selectDate: 'तिथि चुनें',
      selectTime: 'समय चुनें',
      devoteeNames: 'भक्त के नाम',
      devoteeNamesDesc: 'इन नामों में पूजा की जाएगी',
      devoteeNamesPlaceholder: 'नाम दर्ज करें',
      gothram: 'गोत्र',
      gothramPlaceholder: 'गोत्र दर्ज करें',
      nakshatra: 'नक्षत्र',
      nakshatraPlaceholder: 'नक्षत्र चुनें',
      specialRequests: 'विशेष अनुरोध',
      specialRequestsPlaceholder: 'कोई विशेष प्रार्थना या इरादे...',
      poojaDetails: 'पूजा विवरण',
      paymentSummary: 'भुगतान सारांश',
      poojaAmount: 'पूजा राशि',
      prasadDelivery: 'प्रसाद डिलीवरी',
      liveStream: 'लाइव स्ट्रीम',
      totalAmount: 'कुल राशि',
      proceedToPayment: 'भुगतान के लिए आगे बढ़ें',
      note: 'नोट',
      confirmationNote: 'भुगतान पूरा होने के बाद आपको बुकिंग विवरण और लाइव स्ट्रीम लिंक के साथ पुष्टि प्राप्त होगी।',
    },
    bookingConfirmation: {
      title: 'आपकी सेवा अर्पित की गई है',
      subtitle: 'आपके नाम और गोत्र में पूजा की जाएगी। आप और आपके परिवार को आशीर्वाद मिले।',
      bookingConfirmed: 'बुकिंग पुष्टि की गई',
      bookingId: 'बुकिंग आईडी',
      viewJourney: 'पूर्ण यात्रा देखें',
      backToHome: 'होम पर वापस जाएं',
    },
    bookings: {
      title: 'मेरी बुकिंग',
      subtitle: 'अपनी पूजा यात्रा ट्रैक करें',
      active: 'सक्रिय',
      completed: 'पूर्ण',
      noActive: 'कोई सक्रिय बुकिंग नहीं',
      noCompleted: 'कोई पूर्ण बुकिंग नहीं',
      noActiveDesc: 'अपनी पहली पूजा बुक करें',
      noCompletedDesc: 'पूर्ण पूजाएं यहां दिखाई देंगी',
      viewJourney: 'पूर्ण यात्रा देखें',
      watchRecording: 'रिकॉर्डिंग देखें',
      trackPrasad: 'प्रसाद ट्रैक करें',
      poojaJourney: 'पूजा यात्रा',
    },
    journey: {
      title: 'पूजा यात्रा',
      sevaOffered: 'सेवा अर्पित',
      pujariAssigned: 'पुजारी नियुक्त',
      confirmed: 'पुष्टि की गई',
      poojaScheduled: 'निर्धारित',
      goingLive: 'पूजा लाइव',
      poojaCompleted: 'पूर्ण',
      recordingReady: 'रिकॉर्डिंग तैयार',
      prasadPacked: 'प्रसाद पैक किया गया',
      prasadDispatched: 'भेजा गया',
      prasadDelivered: 'वितरित',
    },
    temples: {
      title: 'पवित्र मंदिर',
      subtitle: 'दिव्य मंदिरों का अन्वेषण करें',
      explore: 'अन्वेषण करें',
      hide: 'छुपाएं',
      availablePoojas: 'उपलब्ध पूजा',
      location: 'स्थान',
    },
    profile: {
      title: 'प्रोफ़ाइल',
      personalisation: 'वैयक्तिकरण',
      aiRecommendations: 'आपकी पवित्र सिफारिशें',
      settings: 'सेटिंग्स',
      theme: 'थीम',
      darkMode: 'डार्क मोड',
      lightMode: 'लाइट मोड',
      notifications: 'सूचनाएं',
      hinduCalendar: 'हिंदू कैलेंडर',
      helpSupport: 'सहायता और समर्थन',
      appSettings: 'ऐप सेटिंग्स',
      signOut: 'साइन आउट',
      version: 'भक्ति के साथ बनाया गया',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      editPersonalInfo: 'व्यक्तिगत जानकारी संपादित करें',
      fullName: 'पूरा नाम',
      email: 'ईमेल',
      phone: 'फ़ोन',
      location: 'स्थान',
      nakshatra: 'नक्षत्र',
      rashi: 'राशि',
      dateOfBirth: 'जन्म तिथि',
      gothram: 'गोत्र',
      saveChanges: 'परिवर्तन सहेजें',
      recommendationsTitle: 'आपके नक्षत्र के आधार पर',
      recommendationsDesc: 'आपके लिए व्यक्तिगत पूजा सिफारिशें',
      viewRecommendations: 'सिफारिशें देखें',
      totalPoojas: 'पूजा',
      upcomingCount: 'आगामी',
      devotionScore: 'भक्ति',
    },
    notifications: {
      title: 'सूचना सेटिंग्स',
      poojaReminders: 'पूजा अनुस्मारक',
      poojaRemindersDesc: 'अपनी निर्धारित पूजा से पहले याद दिलाएं',
      liveStreams: 'लाइव स्ट्रीम',
      liveStreamsDesc: 'जब आपकी पूजा स्ट्रीमिंग शुरू हो तो सूचना',
      prasadUpdates: 'प्रसाद अपडेट',
      prasadUpdatesDesc: 'अपने प्रसाद डिलीवरी स्थिति को ट्रैक करें',
      festivalAlerts: 'त्योहार अलर्ट',
      festivalAlertsDesc: 'विशेष पूजा और त्योहार सूचनाएं',
      saveSettings: 'सेटिंग्स सहेजें',
    },
    calendar: {
      title: 'हिंदू कैलेंडर',
      todayTithi: 'आज की तिथि',
      upcomingFestivals: 'आगामी त्योहार',
    },
    help: {
      title: 'सहायता और समर्थन',
      contactSupport: 'समर्थन से संपर्क करें',
      faq: 'अक्सर पूछे जाने वाले प्रश्न',
    },
    language: {
      label: 'भाषा',
      english: 'English',
      telugu: 'తెలుగు',
      hindi: 'हिंदी',
      gujarati: 'ગુજરાતી',
    },
  },
  gu: {
    common: {
      search: 'પૂજા શોધો...',
      viewAll: 'બધું જુઓ',
      upcoming: 'આગામી',
      active: 'સક્રિય',
      completed: 'પૂર્ણ',
      cancel: 'રદ કરો',
      save: 'સાચવો',
      continue: 'ચાલુ રાખો',
      back: 'પાછળ',
      edit: 'સંપાદિત કરો',
      signOut: 'સાઇન આઉટ',
      close: 'બંધ કરો',
      viewDetails: 'વિગતો જુઓ',
      bookNow: 'હમણાં બુક કરો',
      free: 'મફત',
      included: 'સામેલ',
      clearAll: 'અન્ની સાફ કરો',
    },
    nav: {
      home: 'હોમ',
      poojas: 'પૂજા',
      bookings: 'બુકિંગ',
      temples: 'મંદિરો',
      profile: 'પ્રોફાઇલ',
    },
    home: {
      greeting: 'નમસ્તે',
      subtitle: 'આજે એકાદશી છે — વિષ્ણુ પૂજા માટે શુભ દિવસ.',
      featuredTemples: 'વિશેષ મંદિરો',
      categories: 'પૂજા શ્રેણીઓ',
      upcomingPoojas: 'આગામી પૂજા',
      notifications: 'સૂચનાઓ',
      noNotifications: 'કોઈ નવી સૂચના નથી',
      viewNotification: 'જુઓ',
      recommendedForYou: 'તમારા માટે ભલામણ કરેલ',
      basedOnNakshatra: 'તમારા નક્ષત્ર પર આધારિત',
    },
    categories: {
      abhishekam: 'અભિષેક',
      homam: 'હોમમ',
      archana: 'અર્ચના',
      specialPoojas: 'વિશેષ પૂજા',
      all: 'બધી પૂજા',
    },
    poojas: {
      title: 'પવિત્ર પૂજા',
      subtitle: 'પ્રામાણિક મંદિર વિધિઓ શોધો',
      searchPlaceholder: 'પૂજા શોધો...',
      filters: 'ફિલ્ટર્સ',
      noPoojas: 'કોઈ પૂજા મળી નથી',
      liveStream: 'લાઇવ સ્ટ્રીમ ઉપલબ્ધ',
      prasadIncluded: 'પ્રસાદ સામેલ',
      duration: 'અવધિ',
      min: 'મિનિટ',
    },
    poojaDetail: {
      overview: 'વિહંગાવલોકન',
      where: 'ક્યાં',
      how: 'કેવી રીતે',
      why: 'શા માટે',
      offerPooja: 'આ પૂજા અર્પણ કરો',
      sevaAmount: 'સેવા રકમ',
      duration: 'અવધિ',
      liveStreamAvailable: 'લાઇવ સ્ટ્રીમ ઉપલબ્ધ',
      prasadIncluded: 'પ્રસાદ સામેલ',
      whereTitle: 'આ પૂજા ક્યાં આયોજિત કરવામાં આવે છે',
      howTitle: 'આ પૂજા કેવી રીતે આયોજિત કરવામાં આવે છે',
      whyTitle: 'ભક્તો આ પૂજા શા માટે અર્પણ કરે છે',
      suitableForRashi: 'રાશિ માટે યોગ્ય',
      blessings: 'આશીર્વાદ',
    },
    booking: {
      selectDateTime: 'તારીખ અને સમય પસંદ કરો',
      yourDetails: 'તમારી વિગતો',
      reviewConfirm: 'સમીક્ષા અને પુષ્ટિ કરો',
      selectDate: 'તારીખ પસંદ કરો',
      selectTime: 'સમય પસંદ કરો',
      devoteeNames: 'ભક્તોના નામ',
      devoteeNamesDesc: 'આ નામોમાં પૂજા કરવામાં આવશે',
      devoteeNamesPlaceholder: 'નામ દાખલ કરો',
      gothram: 'ગોત્ર',
      gothramPlaceholder: 'ગોત્ર દાખલ કરો',
      nakshatra: 'નક્ષત્ર',
      nakshatraPlaceholder: 'નક્ષત્ર પસંદ કરો',
      specialRequests: 'વિશેષ વિનંતીઓ',
      specialRequestsPlaceholder: 'કોઈ ચોક્કસ પ્રાર્થના અથવા ઇરાદા...',
      poojaDetails: 'પૂજા વિગતો',
      paymentSummary: 'ચુકવણી સારાંશ',
      poojaAmount: 'પૂજા રકમ',
      prasadDelivery: 'પ્રસાદ ડિલિવરી',
      liveStream: 'લાઇવ સ્ટ્રીમ',
      totalAmount: 'કુલ રકમ',
      proceedToPayment: 'ચુકવણી માટે આગળ વધો',
      note: 'નોંધ',
      confirmationNote: 'ચુકવણી પૂર્ણ થયા પછી તમને બુકિંગ વિગતો અને લાઇવ સ્ટ્રીમ લિંક સાથે પુષ્ટિ પ્રાપ્ત થશે.',
    },
    bookingConfirmation: {
      title: 'તમારી સેવા અર્પણ કરવામાં આવી છે',
      subtitle: 'તમારા નામ અને ગોત્રમાં પૂજા કરવામાં આવશે. તમને અને તમારા પરિવારને આશીર્વાદ મળો.',
      bookingConfirmed: 'બુકિંગ પુષ્ટિ થઈ',
      bookingId: 'બુકિંગ આઈડી',
      viewJourney: 'સંપૂર્ણ યાત્રા જુઓ',
      backToHome: 'હોમ પર પાછા જાઓ',
    },
    bookings: {
      title: 'મારી બુકિંગ',
      subtitle: 'તમારી પૂજા યાત્રા ટ્રેક કરો',
      active: 'સક્રિય',
      completed: 'પૂર્ણ',
      noActive: 'કોઈ સક્રિય બુકિંગ નથી',
      noCompleted: 'કોઈ પૂર્ણ બુકિંગ નથી',
      noActiveDesc: 'તમારી પહેલી પૂજા બુક કરો',
      noCompletedDesc: 'પૂર્ણ પૂજાઓ અહીં દેખાશે',
      viewJourney: 'સંપૂર્ણ યાત્રા જુઓ',
      watchRecording: 'રેકોર્ડિંગ જુઓ',
      trackPrasad: 'પ્રસાદ ટ્રેક કરો',
      poojaJourney: 'પૂજા યાત્રા',
    },
    journey: {
      title: 'પૂજા યાત્રા',
      sevaOffered: 'સેવા અર્પણ',
      pujariAssigned: 'પુજારી સોંપાયેલ',
      confirmed: 'પુષ્ટિ થઈ',
      poojaScheduled: 'સુનિશ્ચિત',
      goingLive: 'પૂજા લાઇવ',
      poojaCompleted: 'પૂર્ણ',
      recordingReady: 'રેકોર્ડિંગ તૈયાર',
      prasadPacked: 'પ્રસાદ પેક થયું',
      prasadDispatched: 'મોકલ્યું',
      prasadDelivered: 'વિતરિત',
    },
    temples: {
      title: 'પવિત્ર મંદિરો',
      subtitle: 'દિવ્ય મંદિરોનું અન્વેષણ કરો',
      explore: 'અન્વેષણ કરો',
      hide: 'છુપાવો',
      availablePoojas: 'ઉપલબ્ધ પૂજા',
      location: 'સ્થાન',
    },
    profile: {
      title: 'પ્રોફાઇલ',
      personalisation: 'વ્યક્તિગતકરણ',
      aiRecommendations: 'તમારી પવિત્ર ભલામણો',
      settings: 'સેટિંગ્સ',
      theme: 'થીમ',
      darkMode: 'ડાર્ક મોડ',
      lightMode: 'લાઇટ મોડ',
      notifications: 'સૂચનાઓ',
      hinduCalendar: 'હિન્દુ કેલેન્ડર',
      helpSupport: 'સહાય અને સપોર્ટ',
      appSettings: 'એપ સેટિંગ્સ',
      signOut: 'સાઇન આઉટ',
      version: 'ભક્તિ સાથે બનાવેલ',
      editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
      editPersonalInfo: 'વ્યક્તિગત માહિતી સંપાદિત કરો',
      fullName: 'પૂરું નામ',
      email: 'ઇમેઇલ',
      phone: 'ફોન',
      location: 'સ્થાન',
      nakshatra: 'નક્ષત્ર',
      rashi: 'રાશિ',
      dateOfBirth: 'જન્મ તારીખ',
      gothram: 'ગોત્ર',
      saveChanges: 'ફેરફારો સાચવો',
      recommendationsTitle: 'તમારા નક્ષત્ર પર આધારિત',
      recommendationsDesc: 'તમારા માટે વ્યક્તિગત પૂજા ભલામણો',
      viewRecommendations: 'ભલામણો જુઓ',
      totalPoojas: 'પૂજા',
      upcomingCount: 'આગામી',
      devotionScore: 'ભક્તિ',
    },
    notifications: {
      title: 'સૂચના સેટિંગ્સ',
      poojaReminders: 'પૂજા રીમાઇન્ડર્સ',
      poojaRemindersDesc: 'તમારી સુનિશ્ચિત પૂજા પહેલાં રીમાઇન્ડર મેળવો',
      liveStreams: 'લાઇવ સ્ટ્રીમ્સ',
      liveStreamsDesc: 'જ્યારે તમારી પૂજા સ્ટ્રીમિંગ શરૂ થાય ત્યારે સૂચના',
      prasadUpdates: 'પ્રસાદ અપડેટ્સ',
      prasadUpdatesDesc: 'તમારા પ્રસાદ ડિલિવરી સ્થિતિ ટ્રેક કરો',
      festivalAlerts: 'તહેવાર ચેતવણીઓ',
      festivalAlertsDesc: 'વિશેષ પૂજા અને તહેવાર સૂચનાઓ',
      saveSettings: 'સેટિંગ્સ સાચવો',
    },
    calendar: {
      title: 'હિન્દુ કેલેન્ડર',
      todayTithi: 'આજની તિથિ',
      upcomingFestivals: 'આગામી તહેવારો',
    },
    help: {
      title: 'સહાય અને સપોર્ટ',
      contactSupport: 'સપોર્ટનો સંપર્ક કરો',
      faq: 'વારંવાર પૂછાતા પ્રશ્નો',
    },
    language: {
      label: 'ભાષા',
      english: 'English',
      telugu: 'తెలుగు',
      hindi: 'हिंदी',
      gujarati: 'ગુજરાતી',
    },
  },
};